apiVersion: apps/v1
kind: Deployment
metadata:
  name: sersan
  labels:
    app: sersan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sersan
  template:
    metadata:
      labels:
        app: sersan
    spec:
      containers:
      - name: sersan
        image: dimasaryoprakoso/sersan:1.0
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "4444"
        ports:
        - containerPort: 4444
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /health
            port: 4444
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 2
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 20Mi
        volumeMounts:
        - mountPath: /app/config
          name: browsers
          readOnly: true
      volumes:
      - configMap:
          defaultMode: 420
          name: sersan-browsers
        name: browsers
 
---
apiVersion: v1
kind: Service
metadata:
  name: sersan
spec:
  selector:
    app: sersan
  ports:
  - protocol: TCP
    port: 4444
    targetPort: 4444
